Use python3.10, use traps to deactivate the virtual environment

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,28 +1,28 @@
 #!/usr/bin/env bash
 
+PYTHON="python3.10"
+
+# Fail if anything fails
+set -e
+
 script_dir=$(dirname "$0")
 venv_dir="$script_dir/env"
 
 #Activate virtual environment
-do_deactivate=
 if [[ -z "$VIRTUAL_ENV" ]]; then
-    do_deactivate=yes
     if ! [[ -d "$venv_dir" ]]; then
         echo "Initializing virtual env in $venv_dir"
-        python3.9 -m venv "$venv_dir"
+        "$PYTHON" -m venv "$venv_dir"
         source "$venv_dir/bin/activate"
+        trap deactivate EXIT
         echo "Loading requirements"
         pip install -r "$script_dir/requirements.txt"
     else
         source "$venv_dir/bin/activate"
+        trap deactivate EXIT
     fi
 fi
 
 # Run
 python -m circuits "$@"
-rc=$?
-
-# Deactivate virtual environment
-[[ -n "$do_deactivate" ]] && deactivate
-
-exit $rc
+exit $?
